run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Enable mouse support
set -g mouse on

# Use Vim-like keys for pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

