# brew bundle --file=~/dotfiles/Brewfile
# The one inventory for all four machines. Anything that exists on only one
# of them goes through that platform's own manager, not here.

brew "bat"
brew "bitwarden-cli"
brew "btop"
brew "chafa"
brew "cmake"
brew "dust"
brew "eza"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "glow"
brew "go"
brew "imagemagick"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "neovim"
brew "pkgconf"
brew "resvg"
brew "ripgrep"
brew "rustup"
brew "starship"
brew "stow"
brew "tmux"
brew "yazi"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Casks are macOS-only in general; this one installs on linuxbrew too.
cask "claude-code"
