#!/usr/bin/env bash
# Single writer of cursor.kdl. Mirrors the cursor theme/size from the
# DMS-managed dms/cursor.kdl, and hides the cursor while the pointer is disabled
# (derived from inputs.kdl). Run by the pointer toggle and by the Pointer Toggle
# plugin whenever dms/cursor.kdl changes (i.e. when the cursor theme changes in
# DMS), so the theme stays in sync automatically. niri hot-reloads the result.
set -euo pipefail

NIRI="${XDG_CONFIG_HOME:-$HOME/.config}/niri"
DMS="$NIRI/dms/cursor.kdl"
INPUTS="$NIRI/inputs.kdl"
OUT="$NIRI/cursor.kdl"

theme="$(sed -n 's/.*xcursor-theme[[:space:]][[:space:]]*"\([^"]*\)".*/\1/p' "$DMS" 2>/dev/null | head -1)"
size="$(sed -n 's/.*xcursor-size[[:space:]][[:space:]]*\([0-9][0-9]*\).*/\1/p' "$DMS" 2>/dev/null | head -1)"
[ -n "$theme" ] || theme="default"
[ -n "$size" ] || size=24

# Hide the cursor iff the pointer is currently disabled (off active in inputs.kdl).
if grep -qE "^[[:space:]]*off[[:space:]]+// dms-pointer-toggle" "$INPUTS"; then
    hide="    hide-after-inactive-ms 1"
else
    hide="    // hide-after-inactive-ms 1"
fi

new_content="// Auto-generated by sync-cursor.sh — do not hand-edit.
// Mirrors the cursor theme/size from dms/cursor.kdl (kept in sync automatically),
// and hides the cursor while the pointer is disabled (Pointer Toggle / Mod+Shift+M).
cursor {
    xcursor-theme \"$theme\"
    xcursor-size $size
$hide
}"

# Only write (and thus trigger a niri reload) when the content actually changes.
if [ ! -f "$OUT" ] || [ "$new_content" != "$(cat "$OUT")" ]; then
    printf '%s\n' "$new_content" > "$OUT"
fi
